import { capDataType } from "../type/types";

export const dadosTabelaMocado: capDataType[] = [
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Bone Gigantesto da colina",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#123",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: true,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
  },
  {
    nomeModel: "Boné Vasco",
    tipoRecorte: "Frente",
    modeloDisponivel: "Trucker",
    sku: "#124",
    tecido: "Linho",
    coresTecido: "Azul marinho",
    ordermExibicao: 5,
    status: false,
    criateAt: "21-03-2025",
    updateAt: "21-05-2025",
    imagemUrl:
      "https://firebasestorage.googleapis.com/v0/b/seubone-b5b52.firebasestorage.app/o/images%2F1747915914739_tran-mau-tri-tam-FbhNdD1ow2g-unsplash-2048x1365.jpg.webp?alt=media&token=6fcccc9f-cc81-4b40-9ac4-1a9b6f552bad",
  },
];
